export interface Category {
  name: string;
  easy: string;
  medium: string;
  hard: string;
}

export const wildcardCategory = {
  name: "Miscellaneous",
  easy: `a common word`,
  medium: `a common word for advanced concept`,
  hard: `a less common word`,
};

export const categories: Category[] = [
  {
    name: "Idioms and Expressions",
    easy: "",
    medium: "a common idiom or expression",
    hard: "a less common idiom or expression",
  },
  {
    name: "Civilizations and Empires",
    easy: "",
    medium: "",
    hard: "a well-known ancient civilization",
  },
  {
    name: "Inventions and Breakthroughs",
    easy: "a significant invention which changed a world",
    medium: "a significant invention but abstract",
    hard: "",
  },
  {
    name: "Landmarks",
    easy: "a world famous human made landmark",
    medium: "a famous natural landmark",
    hard: "",
  },
  {
    name: "Space Exploration",
    easy: "a famous astronaut or agency or spacecraft",
    medium: "a famous space mission or space object",
    hard: "",
  },
  {
    name: "Explorers",
    easy: "",
    medium: "a famouse but fictional explorer or expedition",
    hard: "a famous explorer from history",
  },
  {
    name: "Actors and Directors",
    easy: "a Hollywood A-list actor or famous director",
    medium: "a respected character actor or indie director",
    hard: "",
  },
  {
    name: "Movies",
    easy: "a popular blockbuster movie",
    medium: "a critically acclaimed film",
    hard: "an art house or foreign language film",
  },
  {
    name: "Songs",
    easy: "",
    medium: "a chart-topping hit song",
    hard: "a classic song from a specific genre",
  },
  {
    name: "TV Shows",
    easy: "",
    medium: "a popular current TV series",
    hard: "a cult classic TV show",
  },
  {
    name: "Music Artists",
    easy: "",
    medium: "a mainstream pop star",
    hard: "an influential musician in a specific genre",
  },
  {
    name: "Video Games",
    easy: "a cult pc game",
    medium: "a very popular console game",
    hard: "a classic video game from 90s",
  },
  {
    name: "Fictional Characters",
    easy: "a widely recognized fictional character",
    medium: "a popular character from a specific fandom",
    hard: "a lesser-known character from literature or media",
  },
  {
    name: "Celebrities",
    easy: "a current A-list celebrity",
    medium: "a famous person from a specific field",
    hard: "a historical figure or niche celebrity",
  },
  {
    name: "Brands",
    easy: "",
    medium: "a globally recognized brand",
    hard: "a popular brand in a specific industry",
  },
  {
    name: "Books & Authors",
    easy: "",
    medium: "",
    hard: "a bestselling author or book",
  },
  {
    name: "Cartoons & Anime",
    easy: "a popular current or classic cartoon or anime",
    medium: "a cult animated series",
    hard: "an obscure or adult-oriented animated show",
  },
  {
    name: "Sports Teams",
    easy: "",
    medium: "a world-famous sports team",
    hard: "",
  },
  {
    name: "Mythology & Folklore",
    easy: "",
    medium: "a well-known mythological figure",
    hard: "a mythological creature or legend",
  },
  {
    name: "Technology",
    easy: "",
    medium: "a common tech gadget",
    hard: "a well known technology used by profesionals",
  },
  {
    name: "Food & Drinks",
    easy: "",
    medium: "a world famous food or dish",
    hard: "a well known regional specialty",
  },
  {
    name: "Superheroes & Villains",
    easy: "a mainstream superhero superhero",
    medium: "a mainstream comic book villain",
    hard: "",
  },
  {
    name: "Historical Figures",
    easy: "a well-known historical figure",
    medium: "a well-known historical figure a woman",
    hard: "",
  },
  {
    name: "Animals",
    easy: "a common household pet or farm animal",
    medium: "a well known aquatic animal",
    hard: "a well known exotic animal",
  },
  {
    name: "Transportation",
    easy: "a well known vehicle with wheels",
    medium: "a well known but historical vehicle",
    hard: "",
  },
  {
    name: "Science",
    easy: "",
    medium: "",
    hard: "a basic scientific concept",
  },
  {
    name: "Fantasy Worlds",
    easy: "",
    medium: "a well-known fantasy world from movies",
    hard: "a well-known fantasy world from books",
  },
  {
    name: "Fantasy Characters",
    easy: "a famous fantasy character",
    medium: "",
    hard: "a supporting character from a popular fantasy series",
  },
  {
    name: "Political Figures",
    easy: "a significant historical political figure",
    medium: "a significant but controversial political figure",
    hard: "a well-known current political leader",
  },
  {
    name: "Countries",
    easy: "a major world power or popular tourist destination",
    medium: "a known non-western country",
    hard: "non-major African country",
  },
  {
    name: "Cities",
    easy: "a famous global metropolis",
    medium: "a notable regional capital or cultural hub",
    hard: "an obscure or historical city",
  },
  {
    name: "Musical Instruments",
    easy: "",
    medium: "a common orchestral or band instrument",
    hard: "a traditional instrument from a specific culture",
  },
  {
    name: "Plants & Trees",
    easy: "",
    medium: "a common houseplant or garden flower",
    hard: "a specific tree species or exotic plant",
  },
  {
    name: "Video Game Characters",
    easy: "an iconic video game protagonist",
    medium: "a popular supporting character",
    hard: "a retro game character",
  },
  {
    name: "Famous Painters",
    easy: "",
    medium: "a famous painter",
    hard: "",
  },
  {
    name: "Art",
    easy: "an iconic piece of art",
    medium: "a well-known art",
    hard: "a less known art piece",
  },
  {
    name: "Weapons",
    easy: "a famous war weapon",
    medium: "a historical weapon",
    hard: "",
  },
  {
    name: "Time Periods",
    easy: "",
    medium: "a major historical era",
    hard: "a fantasy or prehistoric era",
  },
  {
    name: "Sports",
    easy: "a well-known sport",
    medium: "an extreme sport",
    hard: "",
  },
  {
    name: "Natural Disasters and Catastrophes",
    easy: "a common natural disaster",
    medium: "a specific historical disaster",
    hard: "",
  },
  {
    name: "Olympic Games",
    easy: "a popular Olympic sport",
    medium: "",
    hard: "",
  },
  {
    name: "Monsters from Movies",
    easy: "an iconic movie monster",
    medium: "",
    hard: "",
  },
  {
    name: "Marine Life",
    easy: "a well-known sea creature",
    medium: "a specific species of fish",
    hard: "a rare or deep-sea organism",
  },
  {
    name: "Water",
    easy: "a world famous sea",
    medium: "a major world famous river",
    hard: "a major world famous lake",
  },
  {
    name: "Mountains & Peaks",
    easy: "",
    medium: "a world famous mountain peak",
    hard: "a famous moutain range",
  },
  {
    name: "Kings & Queens",
    easy: "",
    medium: "",
    hard: "a world famous historical ruler",
  },
  {
    name: "Conspiracy Theories",
    easy: "",
    medium: "",
    hard: "a world famous conspiracy theory",
  },
  {
    name: "Famous Duos",
    easy: "an iconic pair from pop culture",
    medium: "a well-known historical or literary duo",
    hard: "an obscure or unexpected famous pair",
  },
  {
    name: "Historical Events",
    easy: "a major historical event",
    medium: "a revolutionary event which changed society",
    hard: "",
  },
];
